---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023 The Linux Foundation

name: "gradle-build"
description: "Setup a specific JDK version and run gradle build"

inputs:
  jdk-version:
    description: "OpenJDK version"
    required: false
  java-version-file: # Mandatory if jdk-version is NOT set
    description: "The path to a file containing java version"
    required: false
  distribution:
    description: "Java distribution"
    required: false
    default: "temurin"

runs:
  using: "composite"
  steps:
    - name: Setup JDK
      id: setup-jdk
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.jdk-version }}
        distribution: ${{ inputs.distribution }}
        java-version-file: ${{ inputs.java-version-file }}
    - name: Setup Gradle
      id: setup-gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      id: run-gradle-build
      shell: bash
      run: ./gradlew build
